# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - ldflags:
      - -s -w -X "main.version={{ .Version }}"
  - main: main.go
    binary: tfswitch
    id: tfswitch
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  -
    # ID of this archive.
    # Defaults to `default`.
    id: tfswitch

    # Builds reference which build instances should be archived in this archive.
    builds:
      - tfswitch
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE

brews:
  -
    name: tfswitch
    ids:
      - tfswitch

    tap:
      owner: versus
      name: homebrew-tap

    commit_author:
      name: versus
      email: versus.dev@gmail.com
    folder: Formula
    caveats: "Type 'tfswitch' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux"
    homepage: "https://versus.github.io/terraform-switcher"
    description: "The tfswitch command lets you switch between terraform versions."
    skip_upload: false

    conflicts:
      - terraform

    test: |
      system "#{bin}/tfswitch --version"

    install: |
      bin.install "tfswitch"
